### ISSUE TITLE
Timestamp in writefile=TRUE CSV export

### ISSUE THREAD

**Issue by amandamcgow** [bhelsel/agcounts#8]
When I set write.file = TRUE the CSV file timestamp is a string of numbers I can't decipher:
<img width="391" alt="Screen Shot 2022-05-13 at 10 46 08 AM" src="https://user-images.githubusercontent.com/55999656/168309469-15a713f5-7381-4ab5-8bd1-5dfc5b39ce38.png">

I am able to fix this by using my own function calling write.csv from utils package in R, the time stamp matches the output from the get_counts function:
<img width="471" alt="Screen Shot 2022-05-13 at 10 48 44 AM" src="https://user-images.githubusercontent.com/55999656/168309589-588222b9-2e5d-4beb-8270-b60c1fd28586.png">

Unsure if other users are having the same issue so wanted to open issue in case.

**Comment by bhelsel** [comment]
Thanks for opening this issue @amandamcgow. I'll look into it. 

@paulhibbing you switched the write.file to `data.table::fwrite` on your first pull request. Is this a common problem with this function? Have you experienced it before?

**Comment by bhelsel** [comment]
@amandamcgow it looks like `data.table::fwrite` function treats R date variables by writing them to ISO as the default. I think this is causing issues either because the time variable is not in ISO format or CSV files don't recognize the ISO format. 

The benefit of `data.table::fwrite` is that it is a faster function than `write.csv` but it seems that this is causing a problem with the timestamp. I'll fix this in the new version that I'm working on now. A temporary fix is to pass the additional argument `dateTimeAs = "write.csv"` into the get_counts function. This passes the `dateTimeAs = "write.csv"` argument to the `...` within the `data.table::fwrite` call.

`agcounts::get_counts(path = path, frequency = 60, epoch = 60, write.file = TRUE, verbose = TRUE, return.data = FALSE, dateTimeAs = "write.csv")`

Let me know if this works for you!

Brian

**Comment by amandamcgow** [comment]
Brian,

BINGO! That call works. I appreciate you looking into this & digging agcounts so far - thanks! 

Cheers,

Amanda

**Comment by bhelsel** [comment]
`dateTimeAS = "write.csv"` was added to `data.table::fwrite` in [agcounts v0.3.0](https://github.com/bhelsel/agcounts/releases/tag/v0.3.0).
